name: fresh_keep_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  go_router: ^14.6.2
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  fpdart: ^1.1.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
